name: Deploy to EC2
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to your app directory
          cd /home/ubuntu/actions-runner/_work/Vescueye-Deploy/Vescueye-Deploy/code/backend
          
          # Pull latest code from GitHub
          git pull origin main
          
          # Install/update dependencies
          npm install
          
          # Create .env file from the secret
          cat << 'EOF' > .env
          ${{ secrets.VESCUEYE_SECRETS }}
          EOF
          
          # Stop existing process if it exists, then start fresh
          pm2 delete vescueye-backend-app 2>/dev/null || true
          pm2 start server.js --name vescueye-backend-app
          
          # Save PM2 configuration
          pm2 save
