name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to your app directory
          cd /home/ubuntu/vescueye-backend
          
          # Pull latest code from GitHub
          git pull origin main
          
          # Install/update dependencies
          npm install
          
          # Create .env file from the secret
          cat << 'EOF' > .env
          ${{ secrets.VESCUEYE_SECRETS }}
          EOF
          
          # Restart your application with PM2
          pm2 restart vescueye-backend || pm2 start app.js --name vescueye-backend
          
          # Save PM2 configuration
          pm2 save
