name: Deploy vescueye to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: code/mobile-app/Backend
        run: npm ci

      - name: Recreate .env file from GitHub Secret
        working-directory: code/mobile-app/Backend
        run: |
          echo "${{ secrets.MOBILE_SECRETS }}" > .env

      - name: Start or reload app with PM2
        working-directory: code/mobile-app/Backend
        run: pm2 startOrReload ecosystem.config.js --env production
